### ISSUE TITLE
Azure - Action to Trigger Logic App not working

### ISSUE THREAD

**Issue by jainankurp** [cloud-custodian/cloud-custodian#4502] opened 2019-08-05 13:01 UTC
@stefangordon i am trying to trigger logic app from policy Actions but connection is getting refused. I can see call were reaching to logic app in the activity log.
Logic app has http trigger as starting point and send email notification actions, 
Manual trigger for logic app is working well.

Sample Policy - 
******************************************************
policies:
  - name: azure-notification
    description: |
      Resource groups without the mandatory tags.
    resource: azure.resourcegroup
    filters:
        - "tag:CostCenter" : absent
        - "tag:Application": absent
        - "tag:Environment": absent
        - "tag:Consumer": absent 
        - "tag:Division": absent
    actions:
      - type: logic-app
        resource-group: cloud-custodian
        logic-app-name: cclogicapp
        batch: false
************************************************************
below is the error message - 
2019-08-02 17:50:16,837: urllib3.connectionpool:WARNING Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x000001D543147048>: Failed to establish a new connection: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond')': /workflows/d0b25214b0854c26b4cd825c5249298a/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=DOcxgDV0uaqPFAG_UCX29mQ32FvEY-X5IdBR6EZEtLg

And i am following this article to setup -
https://github.com/cloud-custodian/cloud-custodian/blob/f10ebd38707018d7643c6075da828e3d6cc6d443/docs/source/azure/examples/logicappnotifications/logicappnotification.rst 

Any pointers will be helpful t resolve this issue.

**Comment by jainankurp** [comment] 2019-08-06 14:10
@stefangordon Stefan, Any inputs from your side? Is this action works at your end?

**Comment by stefangordon** [comment] 2019-08-06 14:51
Hey @jainankurp yes I am not yet sure how to reproduce the failure.

The http error appears to indicate the logic app can not be reached.  Do you have any special networking configurations such as firewalls or vnets enabled on the logic app or the location that Cloud Custodian is running from?

You mentioned you saw activity logs on logic app, but I am guessing these were from us looking up the trigger endpoint via the Management API and not us successfully calling the trigger endpoint.

You can also try calling this trigger endpoint yourself by copying the URL from the error and see if you can trigger it from a web browser.

**Comment by stefangordon** [comment] 2019-08-06 14:55
Adding @aluong as he wrote up these instructions

**Comment by jainankurp** [comment] 2019-08-06 16:11
Weird, I can see this activity which makes me feel that custodian is trying to call logic app but call wasn't successful. "AA-CloudCustodian" is service principal name under which i am executing the policy.
![CC_error](https://user-images.githubusercontent.com/52048623/62556329-9e9dba00-b842-11e9-88e8-53609a1444ea.png)

when i call the endpoint url from web browser from the machine which has custodian. I got this message. i believe this is expected as i am not passing any params.
{"error":{"code":"TriggerRequestMethodNotValid","message":"The HTTP method for this request is not valid: expected 'POST' and actual 'GET'."}}

**Comment by aluong** [comment] 2019-08-06 16:17
@jainankurp are you able to invoke the Logic App (ex: using `curl`) on the same machine you are running Custodian?

**Comment by jainankurp** [comment] 2019-08-06 16:33
@aluong I have used PostMan app and it's able to invoke the logic app via "POST". However, making a "GET" request giving message "{"error":{"code":"TriggerRequestMethodNotValid","message":"The HTTP method for this request is not valid: expected 'POST' and actual 'GET'."}}".

This is logic app design.
![image](https://user-images.githubusercontent.com/52048623/62558044-38b33180-b846-11e9-838d-858801a19493.png)

**Comment by stefangordon** [comment] 2019-08-06 16:35
> Weird, I can see this activity which makes me feel that custodian is trying to call logic app but call wasn't successful. "AA-CloudCustodian" is service principal name under which i am executing the policy.
> ![CC_error](https://user-images.githubusercontent.com/52048623/62556329-9e9dba00-b842-11e9-88e8-53609a1444ea.png)

Yeah so activity log is us making an AD authenticated call to find the HTTP trigger endpoint for you:
e.g. to lookup this URL:
/workflows/d0b25214b0854c26b4cd825c5249298a/triggers/manual/paths/invoke?api-version=2016-06-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=DOcxgDV0uaqPFAG_UCX29mQ32FvEY-X5IdBR6EZEtLg

Then after that we try to do a POST to that url, which is the part that is failing.

**Comment by jainankurp** [comment] 2019-08-06 16:40
@stefangordon yes, it is the same url, i am making POST call.

how this action is working at your end? 
do you have any specific configs which were not mentioned in documentation.

**Comment by aluong** [comment] 2019-08-06 17:18
@jainankurp the `logic-app` is essentially a wrapper around the [webook action](https://cloudcustodian.io/docs/actions.html#webhook-action) that fetches the url programmatically. Can you try switching to a webhook and see if you see the same issue?

**Comment by stefangordon** [comment] 2019-08-06 17:31
Agreed just drop that same URL from the POST call in as the `url` field, and change action type to `webhook` - the only difference between the two is that `logicapp` looks up and sets the URL field for you.  Curious if it works that way.

**Comment by jainankurp** [comment] 2019-08-06 18:08
unfortunately, i am getting same error message after changing type to webhook. This is sample actions from policy.
actions:
      - type: webhook
        url: https://prod-23.eastus.logic.azure.com/workflows/d0b25214b0854c26b4cd825c5249298a/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=DOcxgDV0uaqPFAG_UCX29mQ32FvEY-X5IdBR6EZEtLg  
        batch: false

**Comment by stefangordon** [comment] 2019-08-06 18:22
In this case the totality of the error is `A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond`

Wherever you are running Custodian from is not able to access that URL.  

Are you running Custodian at the command prompt locally? Or in an Azure Function? 

I'm suspecting it may be some proxy configuration that is available in postman but not in the webhook (as we don't have proxy support). 

(I can run your policy against your logic app URL without any error)

**Comment by stefangordon** [comment] 2019-08-06 18:25
https://github.com/cloud-custodian/cloud-custodian/issues/4525

**Comment by jainankurp** [comment] 2019-08-07 17:06
@stefangordon @aluong i have deployed Custodian to a new Internet vm (without proxy). I can see the logic-app is getting triggered but i am getting below error in Custodian that "Message: Resource group 'ResourceGroupName' could not be found."

error text -
_File "c:\users\administrator\appdata\local\programs\python\python37\lib\site-packages\azure\mgmt\logic\operations\workflow_triggers_operations.py", line 478, in list_callback_url
    raise exp
msrestazure.azure_exceptions.CloudError: Azure Error: ResourceGroupNotFound

I have double checked and correct resource group exist in Azure. Any thoughts?

**Comment by aluong** [comment] 2019-08-10 04:33
Ok, so it seems like the first issue was because of the Proxy. That was good to know.

I would first try the webhook, so you can see if you can get a working E2E. It doesn't do any smart lookups, so it will just hit the URL you provided directly.

I would double check the subscription and make sure it is the same subscription where your logic app is located. If you are using Azure CLI auth and you have multiple subscriptions, you can list your subscription by doing:

`az account show`

You can set it by doing:

`az account set -s <SUB_ID>`

Alternatively, if you are using Service Principal auth, you need to double check `AZURE_SUBSCRIPTION_ID`.

More details can be found [here](https://cloudcustodian.io/docs/azure/configuration/authentication.html#service-principal).

**Comment by stefangordon** [comment] 2019-08-20 15:21
The issue to adding proxy support is still pending, but I think this issue may be resolved?  Closing and will reopen if needed.

**Closed by stefangordon** 2019-08-20 15:21 UTC
Labels: cloud/azure, kind/bug
