### ISSUE TITLE
AWS Secrets Manager - Needs a modify resource policy action (for Cross-Account remediation)

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#8101] opened 2022-12-28 18:28 UTC
### Describe the feature

Currently AWS Secrets manager has a filter to check for cross-account access but there is no remediation action (remove-statements) for this finding. There is an API call to put a resource policy which might work - https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/secretsmanager.html#SecretsManager.Client.put_resource_policy

### Extra information or context

```
policies:
          - name: aws-secrets-remove-cross-accounts
            resource: aws.secrets-manager
            filters:
              - type: cross-account
            actions:
              - type: remove-statements
                statement_ids: matched
```

**Comment by thisisshi** [comment] 2023-01-17 20:02
this is a dupe of https://github.com/cloud-custodian/cloud-custodian/issues/7647, closing

**Closed by thisisshi** 2023-01-17 20:02 UTC
Labels: kind/enhancement
