### ISSUE TITLE
Azure China cannot be used normally at all. 

### ISSUE THREAD

**Issue by maguohao2018** [cloud-custodian/cloud-custodian#5954] opened 2020-07-14 11:11 UTC
**Describe the bug**
Azure China cannot be used normally at all. The initial account authentication failed. Please fix it as soon as possible, the Chinese market is waiting for you.

**Expected behavior**
custodian run --output-dir=. policy.yml
2020-07-14 19:10:24,810: cli.azure.cli.core._session:INFO Failed to load or parse file /root/.azure/azureProfile.json. It will be overridden by default settings.
2020-07-14 19:10:24,814: cli.azure.cli.core._session:INFO Failed to load or parse file /root/.azure/az.json. It will be overridden by default settings.
2020-07-14 19:10:24,814: cli.azure.cli.core._session:INFO Failed to load or parse file /root/.azure/az.sess. It will be overridden by default settings.
2020-07-14 19:10:24,817: custodian.azure.session:ERROR Failed to authenticate with CLI credentials. Please run 'az login' to setup account.

**Background (please complete the following information):**
 - OS: [e.g. MacOS 10.15.2 && Linux CentOS 7.7]
 - Python Version: [e.g. python 3.7]
 - Custodian Version: [e.g. 0.9.4]
 - Tool Version: [if applicable]
 - Cloud Provider: [e.g. azure]
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
   - name: vm
      resource: azure.vm
```

**Additional context**
Azure China is completely unavailable, and the most basic azure account authentication is wrong.

**Comment by kapilt** [comment] 2020-07-14 12:26
there's a pull request specific to different azure regions (china, Germany, etc) #5423 if your interested in contributing or testing it out, please comment on the pull request.

closing as duplicate of #5166 

also related #5172

**Closed by kapilt** 2020-07-14 12:26 UTC
Labels: kind/enhancement
