### ISSUE TITLE
azure - work on routes not just route tables

### ISSUE THREAD

**Issue by erwelch** [cloud-custodian/cloud-custodian#4526] opened 2019-08-06 18:25 UTC

**Comment by stefangordon** [comment] 2019-08-12 15:20
Can we close this for #4175?  That one is about making sure we can filter/action on routes inside a route table.  TBH on whether that is a child resource or more likely just custom filter/action.

**Comment by yayitserica** [comment] 2019-08-13 21:11
Duplicate of #4175 closing it

**Closed by yayitserica** 2019-08-13 21:11 UTC
Labels: NeedsDetails, cloud/azure
