### ISSUE TITLE
aws - step functions resources need tags pulled

### ISSUE THREAD

**Issue by SwatiKulkarni709** [cloud-custodian/cloud-custodian#6241] opened 2020-10-22 15:46 UTC
**Describe the bug**
AWS Custodian Policy for StepFunction does not work with config-poll-rule. There is no error message in the Logs, but the policy does not give expected result.
When tested in our AWS account, Config rule must return 19 Non-Compliant and 1 as Compliant. But it says all 20 as Non-Compliant.
Attached the log file and a sample cloudformation template.

**To Reproduce**
Deploy the policy in your account and check your config rule for stepfunction:

**Expected behavior**
On successful execution of the policy, the config rule should flag the StepFunction with missing required tags as Non-compliant resource.

**Background (please complete the following information):**
 - Python Version:  python 3.8.5
 - Custodian Version: 0.9.7
 - Cloud Provider: AWS
 - Policy: [please exclude any account/sensitive information]

---
```
policies:
  - name: d-stepfunction-required-tags
    resource: aws.step-machine
    description: "Type: Config Rule. Compliance: Tag Validation."
    mode:
      type: config-poll-rule
      schedule: TwentyFour_Hours
    filters:
      - and:
          - or:
              - tag:CostCenter: absent
              - tag:RSMs: absent
              - tag:ApplicationIDName: absent
          - tag:__Exception-StepFunctionTags: absent
```
---
**Additional context**
[step_function_logs.txt](https://github.com/cloud-custodian/cloud-custodian/files/5495769/step_function_logs.txt)
[step_test.txt](https://github.com/cloud-custodian/cloud-custodian/files/5495823/step_test.txt)

**Comment by kapilt** [comment] 2020-10-22 16:25
out of curiosity, could you clarify what value using  `config-poll` mode provides, its seems quite limited in functionality or utility, also your `and` clause is superflous

**Comment by SwatiKulkarni709** [comment] 2020-10-22 16:32
Hi @kapilt Thanks for getting back. AWS config rule does not support the StepFunction resource. Hence I used the config-poll-rule to create a custom config rule.
The config rule gets created but tags all the resources as Compliant.

But when I test the same policy on the command line using the custodian run -s out test.yaml it seems to give the correct number of non-compliant resources.

about the ```and yeah, I can remove that. 

please let me know if you need any further details.

**Comment by SwatiKulkarni709** [comment] 2020-11-02 11:16
Hi @kapilt, do you have an update on the above bug? Thanks.

**Comment by gulati-diksha** [comment] 2020-11-09 20:07
> Hi @kapilt Thanks for getting back. AWS config rule does not support the StepFunction resource. Hence I used the config-poll-rule to create a custom config rule.
> The config rule gets created but tags all the resources as Compliant.
> 
> But when I test the same policy on the command line using the custodian run -s out test.yaml it seems to give the correct number of non-compliant resources.
> 
> about the and yeah, I can remove that.
> 
> please let me know if you need any further details.

Note: There is a correction- All resources are marked as 'non-compliant' resources when the config rule gets created.

**Comment by gulati-diksha** [comment] 2020-11-09 21:42
Here are the logs and policy for only 1 filter.

policy:

```
---
 
policies:
  - name: d-stepfunction-required-tags
    resource: aws.step-machine
    description: "Type: Config Rule. Compliance: Tag Validation."
    mode:
      type: config-poll-rule
      schedule: TwentyFour_Hours
    filters:
      - tag:ApplicationIDName: absent
 
```

Logs: 
[StepFunctionwith1FilterPolicyLogs.docx](https://github.com/cloud-custodian/cloud-custodian/files/5513435/StepFunctionwith1FilterPolicyLogs.docx)

**Comment by FireballDWF** [comment] 2020-11-09 22:24
I suspect the root cause is the same as #6204

**Comment by kapilt** [comment] 2020-11-16 13:30
its unrelated, config-poll-rule doesn't gather data via config because config has no data for these resources, its a service level hack to enable periodic gathering from resources that config doesn't support natively. the issue in 6204 was more to do with translating from config's serialization for a resource it does support to api describe format.

**Comment by kapilt** [comment] 2020-11-16 14:21
while investigating this issue .. it became clear there appear to be service bugs in AWS config wrt to code pipeline, such that it never discovers pipeline tags (codecommit source repo) so the sample policy here will always issues when using config-rule mode, using a mode (cloudtrail, poll, periodic)) where custodian fetches the data from the codepipeline service will behave correctly.

**Comment by kapilt** [comment] 2020-11-16 22:14
nutshell here is just augmenting for tags on step function resources

**Closed** 2020-11-17 13:18 UTC
Labels: kind/bug

**Comment by gulati-diksha** [comment] 2020-11-18 14:33
Thank you @kapilt.
