### ISSUE TITLE
Cross account filter in rest-api returning error while execution

### ISSUE THREAD

**Issue by farisbacker** [cloud-custodian/cloud-custodian#6258] opened 2020-10-30 05:45 UTC
**Describe the bug**
Trying to create a policy to catch rest-api without locked resource policy using cross account filter.

**To Reproduce**
```
  "policies": [
    {
      "name": "core-api-resource-policy",
      "resource": "rest-api",
      "mode": {
        "type": "periodic",
        "schedule": "cron(0 0 ? * SUN *)",
        "role": "arn:aws:iam::*******:role/c7n-LambdaExecutionRole",
        "timeout": 180,
        "tags": {
          "c7n-lambda": "core-api-resource-policy",
          "custodian-info": "mode=periodic:version=0.9.3"
        }
      },
      "filters": [
        {
          "type": "cross-account",
          "everyone_only": "True"
        }
      ]
    }
  ]

```
**Expected behavior**
To get restapi's which has access to everyone

**Background (please complete the following information):**
 - OS: Lambda
 - Python Version: Python 3.8
 - Custodian Version: 0.9.3
 - Cloud Provider:  aws
 - Policy: [please exclude any account/sensitive information]
```yaml
policies: 
 policies:
  - name: core-api-resource-policy
    resource: rest-api
    mode:
      type: periodic
      schedule: "cron(0 0 ? * SUN *)"
      role: arn:aws:iam::{account_id}:role/c7n-LambdaExecutionRole
      timeout: 180
      tags:
        c7n-lambda: core-api-resource-policy
    filters:
        - type: cross-account
          everyone_only: True
```
 - Traceback: 
 [DEBUG]	2020-10-30T05:32:12.756Z	c260f4d0-6674-4023-a1c9-8b914ad61c65	Running policy:core-api-resource-policy resource:rest-api region:eu-west-1 c7n:0.9.3
[ERROR]	2020-10-30T05:32:13.192Z	c260f4d0-6674-4023-a1c9-8b914ad61c65	Error while executing policy
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 291, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/query.py", line 507, in resources
    resources = self.filter_resources(resources)
  File "/var/task/c7n/manager.py", line 121, in filter_resources
    resources = f.process(resources, event)
  File "/var/task/c7n/filters/iamaccess.py", line 303, in process
    return super(CrossAccountAccessFilter, self).process(resources, event)
  File "/var/task/c7n/filters/core.py", line 217, in process
    return list(filter(self, resources))
  File "/var/task/c7n/filters/iamaccess.py", line 342, in __call__
    violations = self.checker.check(p)
  File "/var/task/c7n/filters/iamaccess.py", line 100, in check
    policy = json.loads(policy_text)
  File "/var/lang/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/var/lang/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lang/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)
[ERROR]	2020-10-30T05:32:13.253Z	c260f4d0-6674-4023-a1c9-8b914ad61c65	Error while executing policy
Traceback (most recent call last):
  File "/var/task/c7n/policy.py", line 291, in run
    resources = self.policy.resource_manager.resources()
  File "/var/task/c7n/query.py", line 507, in resources
    resources = self.filter_resources(resources)
  File "/var/task/c7n/manager.py", line 121, in filter_resources
    resources = f.process(resources, event)
  File "/var/task/c7n/filters/iamaccess.py", line 303, in process
    return super(CrossAccountAccessFilter, self).process(resources, event)
  File "/var/task/c7n/filters/core.py", line 217, in process
    return list(filter(self, resources))
  File "/var/task/c7n/filters/iamaccess.py", line 342, in __call__
    violations = self.checker.check(p)
  File "/var/task/c7n/filters/iamaccess.py", line 100, in check
    policy = json.loads(policy_text)
  File "/var/lang/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/var/lang/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/var/lang/lib/python3.8/json/decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

**Additional context**

**Comment by phzietsman** [comment] 2022-08-07 14:39
I'm running into exactly this issue.

Looks like a duplicate of https://github.com/cloud-custodian/cloud-custodian/issues/5878 which has been marked as completed, although I cannot figure out where it was fixed.

**Comment by baolsen** [comment] 2022-08-10 09:20
Reopening here: https://github.com/cloud-custodian/cloud-custodian/pull/7632

**Closed** 2022-08-10 12:33 UTC
Labels: kind/bug
