### ISSUE TITLE
azure - use server-side build for deploying functions.

### ISSUE THREAD

**Issue by aluong** [cloud-custodian/cloud-custodian#5124] opened 2019-11-26 17:55 UTC
https://docs.microsoft.com/en-us/azure/azure-functions/functions-deployment-technologies#remote-build

We will need to update how we package, but this should speed up our deployments and remove the need to manually run sync triggers.

**Comment by kapilt** [comment] 2019-11-27 14:19
this is a duplicate of #5511

**Closed** 2020-03-04 21:37 UTC
Labels: cloud/azure, priority/P2
