### ISSUE TITLE
azure - ensure Event Grid mode works properly with child resources

### ISSUE THREAD

**Issue by logachev** [cloud-custodian/cloud-custodian#4617] opened 2019-08-16 20:06 UTC
We have ARM and not ARM child resources. 

It looks like non-arm child resources now won't work with event triggered mode at all.

ARM resources work differently as if we run it in Pull mode (different API is used, no `c7n:parent-id` property)

**Comment by erwelch** [comment] 2019-10-09 17:44
As an update - non-ARM resources are not supported in Event Grid, per: https://docs.microsoft.com/en-us/azure/event-grid/overview

Will add validation logic to prevent users from adding them as the `resource` in event grid mode.

**Comment by stefangordon** [comment] 2020-04-17 17:58
We have arm child resources as well which are not supported, and should be easy to fix.  Namely storage container.

```
  - name: storage-container-public
    description: |
      Find all storage container with public access
    resource: azure.storage-container
    mode:
      type: container-event
      events: [{
        resourceProvider: 'Microsoft.Storage/storageAccounts/blobServices/containers',
        event: 'write'
        }]
```

**Comment by justinhauer** [comment] 2020-05-04 18:07
@stefangordon what is the status of this? 

I just deployed the following policy:
```
policies:
  - name: azure-auto-tag-creator-resources
    description: |
      Tag all arm resources of the VMs, VNETs and Storage accounts with the
      'Creator Email' tag; looking up to 10 days prior.
    resource: azure.armresource
    mode:
      type: azure-event-grid
      events: ['VmWrite', 'StorageWrite']
    filters:
      - type: resource-type
        values:
          - Microsoft.Network/virtualNetworks
          - Microsoft.Storage/storageAccounts
          - Microsoft.Compute/virtualMachines
    actions:
     - type: auto-tag-user
       tag: CreatorEmail

```
and tried to test it out by deploying a VM. the Azure function triggered and ran with a 200, but the virtual machine wasn't tagged.

I tried this in non-event mode (just invoking from CLI) and the resource tagged successfully.

**Comment by stefangordon** [comment] 2020-05-04 18:13
What custodian version are you running @justinhauer? 

I'd expect #5446 to have made event/pull modes work the same.

It was released ~6 days ago in 0.9.1.0.

**Comment by justinhauer** [comment] 2020-05-04 18:17
Pulled from source on 4/29 (last thursday)and built a new virtual environment from master branch. If I should pull again and redeploy I will do so.

**Comment by justinhauer** [comment] 2020-05-04 18:28
@stefangordon the following policy DOES work, leading me to this again its an issue with child resources under azure.armresource:
```
policies:
  - name: azure-auto-tag-creator-vm
    description: |
      Tag all arm resources of the VMs, VNETs and Storage accounts with the
      'Creator Email' tag; looking up to 10 days prior.
    resource: azure.vm
    mode:
      type: azure-event-grid
      events:
        - resourceProvider: Microsoft.Compute/virtualMachines
          event: write
    filters:
      - "tag:CreatorEmail": null

    actions:
     - type: auto-tag-user
       tag: CreatorEmail
```

**Comment by stefangordon** [comment] 2020-05-04 19:23
Oh ok that is helpful.

Do you have the `armresource` one deployed with app insights logging? 

```
-l azure://<instrumentation_key_guid>
```

Even if you don't it might just be capturing `stdout` to App Insights in the function app anyway.

Wondering if you can see any logs from when it gets a VM event and doesn't write a tag.

**Comment by justinhauer** [comment] 2020-05-04 19:27
I will grab the stdout content and post it here

**Comment by justinhauer** [comment] 2020-05-04 19:42
@stefangordon 
```
Executing 'Functions.azure-auto-tag-creator-resources' (Reason='New queue message detected on 'azure-auto-tag-creator-resources-xxx'.', Id=xxxxx)
Trigger Details: MessageId: xxxxx, DequeueCount: 1, InsertionTime: 5/4/20 5:41:25 PM +00:00
Sending invocation id:xxxx
Posting invocation id:xxx on workerId:xxxx
Running Azure Cloud Custodian Policy
Authenticated [Principal | xxx | Authorization File]
policy: azure-auto-tag-creator-resources invoking action: autotaguser resources: 1
Executed 'Functions.azure-auto-tag-creator-resources' (Succeeded, Id=xxxxx)
```

**Comment by stefangordon** [comment] 2020-05-06 14:10
Thanks! Logs indicate it should have written a tag as there is no code path for not writing one without throwing an exception.  I'm wondering if it is a timing issue of some sort while the VM is being created.

The Activity Log on that Virtual Machine resource should have a write event at roughly the same time stamp.  It would be interesting to see if it shows as success or failed, and perhaps to look at the JSON of the event (all available in the portal).

Also, creating the VM is one way to trigger this, but changing any minor settings in the portal for the VM should also trigger it again.  If it was a timing issue with the VM creation not being complete the first time it might have a different result.

I'm pretty sure we use this basic policy in several places, I'll go verify today whether I can reproduce the behavior.

**Comment by stefangordon** [comment] 2021-01-23 14:51
Closing this with #5610 because I am not currently aware of other ARM child resources that are missing support here.  We can file resource specific issues if we find some that need work.    

There was some other discussion here about tagging but it isn't related to the original issue so we can create new issues there as needed also.

**Closed by stefangordon** 2021-01-23 14:51 UTC
Labels: cloud/azure, kind/bug, priority/P2, scope/medium
