### ISSUE TITLE
multiple resource not working 

### ISSUE THREAD

**Issue by shirishshukla** [cloud-custodian/cloud-custodian#4445] opened 2019-07-25 16:15 UTC
@kapilt , am trying for multiple resources in single call by taking below as reference but not working 
 Ref: https://github.com/cloud-custodian/cloud-custodian/issues/1244

```
policies:
  - name: all_if_lb
    resource: [elb, app-elb]
    description: All internet-facing LB
    filters:
      - Scheme: internet-facing

```

Error:

> On instance['resource']:
>     ['elb', 'app-elb']
>  {'name': 'ELB_IF', 'resource': ['elb', 'app-elb'], 'description': 'Report all ELB with internet-facing schema', 'filters': [{'Scheme': 'internet-facing'}]} is not valid under any of the given schemas
> Failed validating 'anyOf' in schema['properties']['policies']['items']:
>

**Comment by kapilt** [comment] 2019-07-25 16:23
multiple resources are not supported in a single policy at this time.

**Comment by kapilt** [comment] 2019-07-28 15:40
duplicate of #1244

**Closed by kapilt** 2019-07-28 15:40 UTC
