### ISSUE TITLE
Upgrading  from 0.8.31.0 to 0.8.33.0 - assume role error

### ISSUE THREAD

**Issue by nic-b** [cloud-custodian/cloud-custodian#3404] opened 2019-01-21 18:54 UTC
Hey,

`custodian run --output-dir output/logs --assume=arn:aws:iam:<role> <policy>.yml`

Am upgrading from 0.8.31.0 to 0.8.33.0. The above command runs fine in the old version, but i get a AssumeRole error on the newer version:

`ClientError: An error ocurred (AccessDenied) when calling the AssumeRole operation: Access denied`

Presumably there have been changes around AssumeRole? Quick scan of the issues list doesn't throw anything up - are there changes required?

thanks

**Comment by kapilt** [comment] 2019-01-22 21:01
thats weird, investigating

**Comment by kapilt** [comment] 2019-01-22 21:07
works for me locally. is there any special restriction on the role in trust policy document? there haven't been many changes to credentials, that last relevant change was in September to add in user agent dynamically based on policy. Are you using external_id ?

**Comment by kapilt** [comment] 2019-01-22 22:13
i guess the other possibility is that you have some sort of local credential in the environment variable thats differing between those executions (AWS_PROFILE, AWS_*) or a different ec2 instance role thats preventing the role assume.

**Comment by nic-b** [comment] 2019-01-29 10:42
Thanks for getting back to me. Think I've found the 'issue'. tl;dr would be 0.8.33.0 has the correct functionality whereas 0.8.31.0 is a 'feature' ;)

Example running command line:
Role A: I log in and assume this role at the command line initially setting up my AWS credentials.
Role B: The role to use in the c7n run--assume-role

In 0.8.31.0 when i run that command i listed originally, all the calls into AWS, including create lambda etc use 'Role A' (**not** Role B). Role B is only used as the Execution Role for the lambda - i assume this is a bug.

In 0.8.33.0 when I run that command, it correctly tries to first assume into 'Role B' to create the lambda. In my environment I can't assume into Role B when in A.

(I see quite a few changes in policy/ctx which look to support this fix/change).

The fix my side would be not to use --assume-role at the command line, but to use the 'role' tag in the yaml file.


thanks for looking!

**Comment by kapilt** [comment] 2019-01-31 19:52
thanks for the update, that sounds a little strange, --assume on the cli behavior has been pretty consistent, the only changes in the last few releases were reusing cached local sessions across policies instead of creating a new session each policy exec. in either case its sounds like current release has expected behavior, closing.

**Closed by kapilt** 2019-01-31 19:52 UTC
Labels: status/awaiting-response
