### ISSUE TITLE
RDS DeletionProtection filter does not work in Lambda

### ISSUE THREAD

**Issue by steveparker-1984** [cloud-custodian/cloud-custodian#3239] opened 2018-12-13 15:28 UTC
The following policy executed locally correctly identifies RDS instance with no Deletion Protection. However when I deploy it as a periodic lambda, it filters to 0 and detects nothing.

```yml

policies:
  - name: rds-instances-no-deletion-protection
    resource: rds
    description: Detect rds db instances with no deletion protection
    filters:
      - DeletionProtection: false

```

Custodian version is 0.8.32.1

**Comment by kapilt** [comment] 2018-12-14 15:52
thats odd, whats in the lambda function logs? this is just

```
mode:
   type: periodic
   schedule: some_schedule
```?

**Comment by kapilt** [comment] 2018-12-15 04:36
i was able to confirm this, i think the issue is due to version drift on botocore versions in lambda. it looks like the lambda version for 2.7 is pretty ancient, ie. boto3 version:1.7.74 .. we're current depending on ` 1.9.62` in your mode you can specify `packages` as an array of packages that we'll upload... ie.

```
packages:
    - botocore
    - boto3
```

looking at the py3.7 runtime it looks like its 1.9.42

**Comment by kapilt** [comment] 2018-12-16 16:45
I think the long term fix here is moving to layers. At the moment we've eschewed packaging up boto3 as its present in the lambda environment and we'd currently be uploading it per policy. But come every reinvent this sort of issue bites folks due to the version drift/lag in the lambda env. It looks like that drift has become quite acute for the python 2.7 version (1.7.74 was released august 9th).

**Closed** 2019-01-31 19:53 UTC
Labels: area/lambda
