### ISSUE TITLE
RDS snapshot copy-related-tag fails with error

### ISSUE THREAD

**Issue by kethinna** [cloud-custodian/cloud-custodian#8501] opened 2023-04-18 18:00 UTC
### Describe the bug

Attempting to run a copy-related-tag action for copying tags from a RDS instance to RDS snapshots. However, when the policy is run I am met with the following traceback error.

The error is the same as the closed issue https://github.com/cloud-custodian/cloud-custodian/issues/6667 . The policy is exactly the same as well. However we are running the policy across multiple accounts.

To Reproduce
custodian run "./policy.yml" -s ./out -v --profile profile1 --region us-east-1 --debug --trace

After executing this the error occurs

### What did you expect to happen?

RDS snapshots pull tags from the RDS db instance

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.22
Python:      3.10.10 (main, Feb  8 2023, 05:34:50) [Clang 14.0.0 (clang-1400.0.29.202)]
Platform:    posix.uname_result(sysname='Darwin', nodename='bcd07405376c', release='22.3.0', version='Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000', machine='arm64')
Using venv:  True
Docker: False
Installed: 

argcomplete==2.0.0
attrs==22.2.0
boto3==1.26.51
botocore==1.29.51
docutils==0.17.1
importlib-metadata==4.13.0
jmespath==1.0.1
jsonschema==4.17.3
pyrsistent==0.19.3
python-dateutil==2.8.2
pyyaml==6.0
s3transfer==0.6.0
six==1.16.0
tabulate==0.8.10
urllib3==1.26.14
zipp==3.11.0
```

### Policy

```shell
policies: 
   - name: copy-tags-from-rds-to-snapshot
    resource: rds-snapshot
    actions:
      - type: copy-related-tag
        resource: rds
        skip_missing: true
        key: DBInstanceIdentifier
        tags:
          - sometag
```

### Relevant log/traceback output

```shell
Traceback:

2023-04-18 12:24:06,056: custodian.commands:DEBUG Loaded file ./policies: copy.yml. Contains 1 policies
2023-04-18 12:24:06,837: custodian.output:DEBUG Storing output with <LogFile file://./out/Copy-tags-from-redshift-cluster-to-snapshot/custodian-run.log>
2023-04-18 12:24:06,842: custodian.policy:DEBUG Running policy:Copy-tags-from-redshift-cluster-to-snapshot resource:redshift-snapshot region:us-east-1 c7n:0.9.22
2023-04-18 12:24:06,844: custodian.cache:DEBUG expiring stale cache entries
2023-04-18 12:24:10,655: custodian.resources.redshiftsnapshot:DEBUG Filtered from 244 to 244 redshiftsnapshot
2023-04-18 12:24:10,655: custodian.policy:INFO policy:Copy-tags-from-redshift-cluster-to-snapshot resource:redshift-snapshot region:us-east-1 count:244 time:3.81
2023-04-18 12:24:10,665: custodian.cache:DEBUG expiring stale cache entries
2023-04-18 12:24:10,666: custodian.output:DEBUG metric:ResourceCount Count:244 policy:copy-tags-from-redshift-cluster-to-snapshot restype:redshift-snapshot scope:policy
2023-04-18 12:24:10,666: custodian.output:DEBUG metric:PolicyException Count:1 policy:copy-tags-from-redshift-cluster-to-snapshot restype:redshift-snapshot
2023-04-18 12:24:10,666: custodian.output:DEBUG metric:ApiCalls Count:3 policy:copy-tags-from-redshift-cluster-to-snapshot restype:redshift-snapshot
2023-04-18 12:24:10,666: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/policy.py", line 364, in run
    results = a.process(resources)
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/tags.py", line 1098, in process
    related_tag_map = self.get_resource_tag_map(self.data['resource'], related_ids)
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/tags.py", line 1156, in get_resource_tag_map
    for r in manager.get_resources(list(ids))
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/query.py", line 576, in get_resources
    resources = self.source.get_resources(ids)
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/query.py", line 227, in get_resources
    return self.query.get(self.manager, ids)
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/query.py", line 95, in get
    assert len(identities) == 1, "Scalar server side filter"
AssertionError: Scalar server side filter
Traceback (most recent call last):
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/cli.py", line 363, in main
    command(config)
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/commands.py", line 128, in _load_policies
    return f(options, list(policies))
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/commands.py", line 302, in run
    policy()
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/policy.py", line 1332, in __call__
    resources = mode.run()
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/policy.py", line 364, in run
    results = a.process(resources)
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/tags.py", line 1098, in process
    related_tag_map = self.get_resource_tag_map(self.data['resource'], related_ids)
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/tags.py", line 1156, in get_resource_tag_map
    for r in manager.get_resources(list(ids))
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/query.py", line 576, in get_resources
    resources = self.source.get_resources(ids)
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/query.py", line 227, in get_resources
    return self.query.get(self.manager, ids)
  File "/Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/query.py", line 95, in get
    assert len(identities) == 1, "Scalar server side filter"
AssertionError: Scalar server side filter
> /Users/nandakethineni/custodian/lib/python3.10/site-packages/c7n/query.py(95)get()
-> assert len(identities) == 1, "Scalar server side filter"
(Pdb) resource_manager
<c7n.resources.redshift.Redshift object at 0x1047a6590>
(Pdb) resource_manager.type
'redshift'
(Pdb) resource_manager.resource_type
<TypeInfo AWS::Redshift::Cluster>
(Pdb) resource_manager.resource_type.id
'ClusterIdentifier'
(Pdb) identities
['uhrdwp', 'deormdwp', 'fsda-cmf-infinity-qa', 'dhrdwp-gen3', 'dhrdwp']
(Pdb)
```

**Comment by ajkerrigan** [comment] 2023-05-17 00:19
Thanks for the report - this came up again in today's community meeting. I'm going to close this as a duplicate of #6667 which has been reopened since you created this one. Thanks for the bump :+1:

**Closed by ajkerrigan** 2023-05-17 00:19 UTC
Labels: kind/bug
