### ISSUE TITLE
whitelist_orgids missing from cross-account aws.ami

### ISSUE THREAD

**Issue by jare19** [cloud-custodian/cloud-custodian#7031] opened 2021-12-14 18:21 UTC
### Describe the feature

I would like parity with the other cross-account filters and to be able to use the whitelist_orgids key.

**Comment by ajkerrigan** [comment] 2022-01-11 19:26
Thanks @jare19 - this is worth supporting :+1: .

Right now, `whitelist` and `whitelist_from` expect a list of account IDs or the special group ID `all`. I'm thinking instead of adding `whitelist_orgids`, we may want to allow `whitelist`/`whitelist_from` items to be any of the following:

* the special group value `all`
* an account ID
* an organization ID (o-xxxxxx)
* an organizational unit ID (ou-xxxxxx)

That would mean accounting for `OrganizationArn` and `OrganizationalUnitArn` [here](https://github.com/cloud-custodian/cloud-custodian/blob/8fad4f45429f23a3cf97e00adf8f4a87dfa016d2/c7n/resources/ami.py#L355) and testing/documenting the change.

_The reasoning here is that AMI Org/OU-sharing is based on attribute values that seem specific to AMIs. `whitelist_orgids` was designed more for resources that grant cross-account access via resource-level IAM policies, and making it work with AMIs feels a bit awkward._

**Comment by thisisshi** [comment] 2022-12-09 19:30
closed via: https://github.com/cloud-custodian/cloud-custodian/pull/7974

**Closed by thisisshi** 2022-12-09 19:30 UTC
Labels: kind/enhancement
