### ISSUE TITLE
azure - add HDInsight resource

### ISSUE THREAD

**Issue by erwelch** [cloud-custodian/cloud-custodian#4530] opened 2019-08-06 18:29 UTC

**Comment by stefangordon** [comment] 2019-08-12 15:27
Duplicate of #3311 ?

**Comment by yayitserica** [comment] 2019-08-13 20:28
### ACCEPTANCE CRITERIA

1. Follow steps to add a new resource [see [here]](https://cloudcustodian.io/docs/azure/advanced/contribute.html#adding-new-azure-resources)

FYI @erwelch

**Comment by yayitserica** [comment] 2019-09-05 17:14
Duplicate of #3311 [Azure Milestone B]

@stefangordon can you please add this work item [4350] to Azure Milestone B, thanks!

**Closed by yayitserica** 2019-09-05 17:14 UTC
Labels: cloud/azure, kind/duplicate, scope/small
