### ISSUE TITLE
VS Code Custodian Azure Schema Issue

### ISSUE THREAD

**Issue by jtroberts83** [cloud-custodian/cloud-custodian#6223] opened 2020-10-16 05:28 UTC
**Describe the bug**
I found that if I have c7n_azure installed when I output my custodian schema --json > schema.json for my Visual Studio Code that it breaks the schema.json file and Visual Studio Code won't load it and instead throws the error from the custodian VS Code docs 
```
'Request textDocument/hover failed with message: Cannot read property '$ref' of null'
```

**To Reproduce**
pip install c7n
pip install c7n_azure
pip install c7n_gcp
custodian schema --json > schema.json
Open a .yaml file in VS Code (after performing the required settings.json extension config for yaml)
Output console throws the error from above.
If I then perform a pip uninstall c7n_azure and export the schema again it works fine in VS Code.

**Expected behavior**
Something in the Azure schema is interfering and causing the schema.json doc to fail loading in VS Code

**Background (please complete the following information):**
 - OS: [e.g. OSX 10.15] Catalina 10.15.7 OSx
 - Python Version: [e.g. python 3.8.1] 3.8.5
 - Custodian Version: [e.g. 0.8.46.1] 0.9.7.0
 - Tool Version: [if applicable] c7n_azure-0.7.6
 - Cloud Provider: [e.g. gcp, aws, azure] Azure
 - Policy: [please exclude any account/sensitive information]
N/A
 - Traceback: [if applicable, please exclude sensitive/account information] N/A
 - `custodian version --debug` output

```
Custodian:   0.9.7
Python:      3.8.5 (v3.8.5:580fbb018f, Jul 20 2020, 12:11:27) 
             [Clang 6.0 (clang-600.0.57)]
Platform:    posix.uname_result(sysname='Darwin', nodename='MacBook-Pro.localdomain', release='19.6.0', version='Darwin Kernel Version 19.6.0: Mon Aug 31 22:12:52 PDT 2020; root:xnu-6153.141.2~1/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.1
attrs==20.2.0
boto3==1.15.16
botocore==1.18.16
c7n==0.9.7
cachetools==4.1.1
certifi==2020.6.20
chardet==3.0.4
google-api-core==1.22.4
google-api-python-client==1.12.3
google-auth==1.22.1
google-auth-httplib2==0.0.4
google-cloud-core==1.4.3
google-cloud-logging==1.15.1
google-cloud-monitoring==0.34.0
google-cloud-storage==1.31.2
google-crc32c==1.0.0
google-resumable-media==1.1.0
googleapis-common-protos==1.52.0
httplib2==0.18.1
idna==2.10
importlib-metadata==1.7.0
jmespath==0.10.0
jsonpickle==1.3
jsonschema==3.2.0
protobuf==3.13.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
pyrsistent==0.17.3
python-dateutil==2.8.1
pytz==2020.1
pyyaml==5.3.1
ratelimiter==1.2.0.post0
requests==2.24.0
retrying==1.3.3
rsa==4.6
s3transfer==0.3.3
setuptools==47.1.0
six==1.15.0
tabulate==0.8.7
uritemplate==3.0.1
urllib3==1.25.10
zipp==3.3.0
```

**Additional context**
Community member pointed out the issue, I tested and confirmed and found the root cause to be the c7n_azure tool schema

**Comment by kapilt** [comment] 2020-10-16 09:41
duplicate of #6211

**Comment by kapilt** [comment] 2020-10-16 09:42
the clue wrt to azure provider is helpful thanks

**Comment by kapilt** [comment] 2020-10-17 18:29
closing this duplicate in favor of the original issue which has more discussion

**Closed by kapilt** 2020-10-17 18:29 UTC
Labels: kind/bug
