### ISSUE TITLE
how to connect with Azure China

### ISSUE THREAD

**Issue by sdfengw** [cloud-custodian/cloud-custodian#5172] opened 2019-12-15 04:43 UTC
hello, thanks your help in advance！

as you know, azure global and azure china is isolated, I found the default connection is to azure global in custodian. I am wondering how to modify custodian code/parameters, so we could connect to azure china. thanks again!

feng

**Comment by kapilt** [comment] 2019-12-15 14:16
duplicate of #5166

**Closed** 2019-12-15 15:17 UTC
Labels: kind/duplicate
