### ISSUE TITLE
AWS Remove unused Secrets Manager secrets

### ISSUE THREAD

**Issue by pareshcc** [cloud-custodian/cloud-custodian#8150] opened 2023-01-12 14:34 UTC
### Describe the feature

I want to filter unused Secrets Manager secrets then remove/delete, but current [doc](https://cloudcustodian.io/docs/aws/resources/secrets-manager.html#actions) is not supported.

**Comment by ajkerrigan** [comment] 2023-01-12 16:07
Closing as duplicate of #8100

**Closed by ajkerrigan** 2023-01-12 16:07 UTC
Labels: kind/enhancement
