### ISSUE TITLE
mugc in c7n-org 0.9.6 doesn't work when using --prefix

### ISSUE THREAD

**Issue by trollydolly** [cloud-custodian/cloud-custodian#6180] opened 2020-10-06 10:37 UTC
mugc fails to cleanup old policies if --prefix switch is used. We have a combination of 'enforced' policies and user policies so we need to use a prefix on the enforced policies so that mugc doesn't remove user policies. 
Enforced:  mugc used with --prefix 'custodian-global-' (used with just enforced policies with an accounts file that holds all accounts, 300+)
User:         mugc used without --prefix, i.e. using default (used with two policy files, enforced policies and user policies with an accounts file that holds just one account)

Any help, much appreciated
Alex

p.s. this is for AWS

**Comment by kapilt** [comment] 2020-10-06 12:03
you'll need to provide an example of what your doing,  ie what is actual cli (sanitized) your using and also describe what the issue is. ie what does fails mean? what's the output of the cli?  also does it work if your not using c7n-org to run it?

**Comment by trollydolly** [comment] 2020-10-06 13:58
Hi Kapil, attached are sanitized extracts of our 'enforced' policy file and accounts file. The c7n-org, either run or script is via an AWS pipeline that rebuilds a docker image and updates accounts each time policies are updated in a GitHub repo. 

In essence, various testing seems to suggest if we run the mugc.py without a prefix switch, ergo using the default 'custodian-' prefix, everything works okay and old Lambda policies not in the config files are removed. 
If we use the --prefix switch, Lambda policies are redeployed but old policies not evident in the config files are NOT removed.

[user_policies.txt](https://github.com/cloud-custodian/cloud-custodian/files/5334323/user_policies.txt)
[accounts.txt](https://github.com/cloud-custodian/cloud-custodian/files/5334324/accounts.txt)
[enforced_policies.txt](https://github.com/cloud-custodian/cloud-custodian/files/5334325/enforced_policies.txt)

**Comment by kapilt** [comment] 2020-10-06 14:48
do you have  dockerfile for the container, we really need to see what the cli being used is and if its a current version of mugc, and what the log is. --prefix is automatically converted to a --policy-regex. the default value used is effectively `custodian-` for prefix which gets converted to `^custodian-.*`

**Comment by kapilt** [comment] 2020-10-06 15:03
i was able to reproduce with current trunk, investigating

**Comment by kapilt** [comment] 2020-10-06 15:20
feeling like all the machinery/devops around this is maybe overly complicating what the actual issue is.. ie can you just run mugc in dryrun mode to see what its matching directly

`python tools/ops/mugc.py --prefix "custodian-global" --dryrun -c enforced-policies.yml  -v`

**Comment by trollydolly** [comment] 2020-10-07 08:12
The default is exactly what we're after, remove all policies not present in the policy file. I'll try a --dryrun to see what we get and relay back results.

**Comment by trollydolly** [comment] 2020-10-11 10:15
Removing single quotes around the --prefix qualifier has got this to work, i.e.
"/usr/local/bin/python3.8 /home/custodian/cloud-custodian/tools/ops/mugc.py -c /home/custodian/global-policies/policies.yaml -r eu-west-1 --prefix 'custodian-global-' -v" 
changed to ... 
"/usr/local/bin/python3.8 /home/custodian/cloud-custodian/tools/ops/mugc.py -c /home/custodian/global-policies/policies.yaml -r eu-west-1 --prefix custodian-global- -v"

**Comment by kapilt** [comment] 2020-10-12 12:09
ic, so it was related to your devops setup around the tools.. closing issue.

**Closed by kapilt** 2020-10-12 12:09 UTC
