### ISSUE TITLE
Is it possible to get advance nonfiction before deleting  unattached EBS volumes

### ISSUE THREAD

**Issue by ahmadzaikk** [cloud-custodian/cloud-custodian#6530] opened 2021-03-15 20:37 UTC
Hello,

I am trying to cleanup the unattached EBS volumes, for example I want all the unattached EBS volumes to be deleted after 30 days, but I want to get reminder notification like 3 days before the actual deletion accurse, is that possible?

**Comment by ahmadzaikk** [comment] 2021-03-15 20:38
@kapilt  Can you please help me on this?

**Comment by ajkerrigan** [comment] 2021-03-15 21:50
Hi @ahmadzaikk - you can use the example policy that [deletes unused RDS databases](https://cloudcustodian.io/docs/aws/examples/rdsdeleteunused.html?highlight=rds-unused-databases-notify-step2) as guidance here. Specifically, have a look at the `rds-unused-databases-notify-step2` policy which uses the `marked-for-op` filter with the `skew` parameter to send a follow-up notice 7 days prior to deletion.

**Comment by ahmadzaikk** [comment] 2021-03-15 21:53
@ajkerrigan Thanks, let me try.

**Comment by thisisshi** [comment] 2021-03-17 00:16
Like @ajkerrigan said, this can be done by using the mark for op flow, closing

**Closed by thisisshi** 2021-03-17 00:16 UTC
Labels: kind/question

**Comment by ahmadzaikk** [comment] 2021-03-17 17:33
@ajkerrigan Thanks for the instruction, it worked.

**Comment by ahmadzaikk** [comment] 2021-04-05 18:43
@ajkerrigan Hi 

I using the following policy to notify 7 days before deleting the EBS volumes, but it keep sending notification on days 6,5,4,3,2,and 1 before deleting the Volumes, but I only one notification, 7 days before deletion.


- name: ebs-volume-delete-notify-before-deletion
  resource: aws.ebs
  description: |
    days and notify on any unused EBS that have already been marked for delete
  filters:
      # - "tag:ebs_volume_delete_unattached": present
      - type: marked-for-op
        tag: ebs_volume_delete_unattached
        op: delete
        skew: 2
  mode:
    schedule: "rate(24 hours)"
    type: periodic
    role: "arn:aws:iam::{account_id}:role/CloudCustodianLambdaRole"
  actions:
    - type: notify
      template: default.html
      template_format: "html"
      priority_header: "1"
      subject: "EBS Deletion Reminder"
      violation_desc: "The follow EBS volumes will be deleted in 7 days."
      action_desc: "EBS Volumes are not in use"
      slack_template: custodian-slack-ebs-volume-delete-notify-before-deletion
      to:
        - slack,
        - email address
        
      transport:
        type: sqs
        queue: https://my sqs 
      comments: |
        Custodian detected unattached EBS volume(s)

**Comment by ajkerrigan** [comment] 2021-04-06 00:12
That behavior is by design - `skew: 7` matches resources marked for action anytime up to 7 days in the future. It could match resources marked for action today, 5 days from now, or a year in the past. As far as I know if you want to scope it more narrowly than that you'd need another filter. One option is to add a tag to record that you've sent a notice, and avoid sending repeat notices for resources with that tag.

**Comment by ahmadzaikk** [comment] 2021-04-06 00:33
@ajkerrigan Thanks I will try the tag to avoid sending
