### ISSUE TITLE
WAF Tagging

### ISSUE THREAD

**Issue by JohnHillegass** [cloud-custodian/cloud-custodian#5588] opened 2020-04-14 01:33 UTC
**Is your feature request related to a problem? Please describe.**
Currently unable to tag WAF. Adding from gitter, feature request by @rbgit

**Comment by kapilt** [comment] 2020-04-14 15:13
closing as a duplicate of #4623 and let's use that one to track

**Closed by kapilt** 2020-04-14 15:13 UTC
Labels: kind/enhancement
