### ISSUE TITLE
setting MinimumProtocolVersion in Cloudfront distribution fails

### ISSUE THREAD

**Issue by cleo2525** [cloud-custodian/cloud-custodian#6975] opened 2021-11-02 23:15 UTC
### Describe the bug

In the Cloudfront actions, set-attributes, when attempting to change just **MinimumProtocolVersion** under the **ViewerCertificate** attribute, I am forced to hardcode all the attributes, including **ACMCertificateArn** & **Certificate** which can be unique to each Cloudfront Distribution

```
      - type: set-attributes
         attributes:
            ViewerCertificate:
               ACMCertificateArn: "arn:aws:acm:us-east-1:123456789123:certificate/example-cert-arn-a89e-0987654321098"
               SSLSupportMethod: "sni-only"
               MinimumProtocolVersion: "TLSv1.2_2018"
               Certificate: "arn:aws:acm:us-east-1:123456789123:certificate/example-cert-4104-arb-0987654321098"
               CertificateSource: "acm"
```

### What did you expect to happen?

I expect c7n to take the current Cloudfront Distribution settings, which are written, by the filter, to the resources.json  and use those values to populate the required fields for values I have not specified in the **set-attributes** policy.

### Cloud Provider

Amazon Web Services (AWS)

### Cloud Custodian version and dependency information

```shell
Custodian:   0.9.13
Python:      3.9.6 (default, Jun 29 2021, 05:25:02) 
             [Clang 12.0.5 (clang-1205.0.22.9)]
Platform:    posix.uname_result(sysname='Darwin', release='20.6.0', version='Darwin Kernel Version 20.6.0: Mon Aug 30 06:12:21 PDT 2021; root:xnu-7195.141.6~3/RELEASE_X86_64', machine='x86_64')
Using venv:  True
Docker: False
Installed: 

argcomplete==1.12.3
attrs==21.2.0
boto3==1.17.102
botocore==1.20.102
importlib-metadata==4.6.0
jmespath==0.10.0
jsonschema==3.2.0
pyrsistent==0.18.0
python-dateutil==2.8.1
pyyaml==5.4.1
s3transfer==0.4.2
setuptools==56.0.0
six==1.16.0
tabulate==0.8.9
typing-extensions==3.10.0.0
urllib3==1.26.6
zipp==3.4.1
```

### Policy

```shell
policies:
- name: distro-deprecated-tls
  resource: distribution
  filters:
      - or:
          - type: distribution-config
            key: "ViewerCertificate.MinimumProtocolVersion"
            op: equal
            value: "TLSv1.1_2016"
          - type: distribution-config
            key: "ViewerCertificate.MinimumProtocolVersion"
            op: equal
            value: "TLSv1_2016"
          - type: distribution-config
            key: "ViewerCertificate.MinimumProtocolVersion"
            op: equal
            value: "TLSv1"
          - type: distribution-config
            key: "ViewerCertificate.MinimumProtocolVersion"
            op: equal
            value: "SSLv3"
      - or:
          - type: distribution-config
            key: "ViewerCertificate.CertificateSource"
            op: equal
            value: "acm"
          - type: distribution-config
            key: "ViewerCertificate.CertificateSource"
            op: equal
            value: "iam"
      - and:
          - type: marked-for-op
            tag: distro_deprecated_tls
            op: notify
            skew: 0
  actions:
      - type: set-attributes
        attributes:
          ViewerCertificate:
              MinimumProtocolVersion: "TLSv1.2_2018"
```

### Relevant log/traceback output

```shell
2021-10-24 10:46:48,283: custodian.actions:WARNING Exception trying to update Distribution: arn:aws:cloudfront::123456789012:distribution/E2HN2REXAMPLE error: An error occurred (InternalError) when calling the UpdateDistribution operation (reached max retries: 4): 
2021-10-24 10:46:48,284: custodian.output:ERROR Error while executing policy
Traceback (most recent call last):
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/c7n/policy.py", line 322, in run
    results = a.process(resources)
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/c7n/resources/cloudfront.py", line 568, in process
    self.process_distribution(client, d)
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/c7n/resources/cloudfront.py", line 650, in process_distribution
    raise e
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/c7n/resources/cloudfront.py", line 639, in process_distribution
    res = client.update_distribution(
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalError) when calling the UpdateDistribution operation (reached max retries: 4): 
2021-10-24 10:46:48,290: custodian.commands:ERROR Error while executing policy distro-deprecated-tls, continuing
Traceback (most recent call last):
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/c7n/commands.py", line 301, in run
    policy()
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/c7n/policy.py", line 1205, in __call__
    resources = mode.run()
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/c7n/policy.py", line 322, in run
    results = a.process(resources)
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/c7n/resources/cloudfront.py", line 568, in process
    self.process_distribution(client, d)
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/c7n/resources/cloudfront.py", line 650, in process_distribution
    raise e
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/c7n/resources/cloudfront.py", line 639, in process_distribution
    res = client.update_distribution(
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/botocore/client.py", line 386, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/user/cloud-custodian/custodian_venv/lib/python3.9/site-packages/botocore/client.py", line 705, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (InternalError) when calling the UpdateDistribution operation (reached max retries: 4): 
2021-10-24 10:46:48,296: custodian.commands:ERROR The following policies had errors while executing
 - distro-deprecated-tls
```

**Comment by kapilt** [comment] 2021-11-05 19:40
the error code here InternalError implies something not on the custodian client side at first glance, is it reproducible?

**Comment by cleo2525** [comment] 2022-01-15 18:12
Circling back to see if there are any thoughts on this. I am still getting the same error when trying to change the TLS version on a Cloudfront distro using the 'set-attributes' action.

```
  actions:
      - type: set-attributes
        attributes:
          ViewerCertificate:
            MinimumProtocolVersion: "TLSv1.2_2018"

```

If I hard-code all the values, it works

```
  actions:
      - type: set-attributes
        attributes:
           ViewerCertificate:
             ACMCertificateArn: "arn:aws:acm:us-east-1:123456789123:certificate/example-cert-arn-a89e-0987654321098"
             SSLSupportMethod: "sni-only"
             MinimumProtocolVersion: "TLSv1.2_2018"
             Certificate: "arn:aws:acm:us-east-1:123456789123:certificate/example-cert-4104-arb-0987654321098"
             CertificateSource: "acm"
```

**Comment by ajkerrigan** [comment] 2022-06-07 14:55
I looked into this a bit, and I think I see where things are going awry. It looks like the logic [here](https://github.com/cloud-custodian/cloud-custodian/blob/0bfbc4415b3c6aee5005680e254a185a48b1bcdd/c7n/resources/cloudfront.py#L706-L717) does try to merge updated attributes with an existing configuration, but it doesn't merge recursively. That causes this policy to replace the `ViewerCertificate` key of the config entirely, so you need to define all fields for it to work.

As for a solution, it's probably worth trying to use [c7n.utils.merge_dict](https://github.com/cloud-custodian/cloud-custodian/blob/2bf055368c736ebab21b37109f15858f24ed1701/c7n/utils.py#L751-L766) which seems designed for this deep merge case.

I need to confirm this with some tests, this is mostly a fresh acknowledgement of the issue and a placeholder for a potential fix.

**Comment by ajkerrigan** [comment] 2022-06-15 15:17
Hi @cleo2525 - the fix for this is tested/merged and will be included in the next release. Thanks for the samples and context around this bug, they fed directly into the tests!

**Closed by ajkerrigan** 2022-06-15 15:17 UTC
Labels: kind/bug
